Feature/GitHub actions
FredHutch/VISCtemplates pull request #86
Opened 2021-11-30 00:11 UTC by monicagerber

Added GitHub actions with `usethis::use_github_action("check-standard")`, following recommendation from this [blog](https://www.tidyverse.org/blog/2020/04/usethis-1-6-0/). Closes #84

2021-11-30 22:19 UTC, wfulp commented
@monicagerber should we allow actions on GitHub now?
https://github.com/FredHutch/VISCtemplates/settings/actions

2021-11-30 22:28 UTC, wfulp requested changes
Once we add develop to the checks and allows Github actions we can see if the checks pass.

2021-11-30 22:28 UTC, wfulp commented on .github/workflows/check-standard.yaml
> +    branches: [main, master]
```suggestion
    branches: [main, master, develop]
```
It should be fine adding the checks for develop branch too.

2021-11-30 22:28 UTC, wfulp commented on .github/workflows/check-standard.yaml
> +    branches: [main, master]
```suggestion
    branches: [main, master, develop]
```

2021-12-01 01:08 UTC, monicagerber commented
I'm not able to change this: 
![image](https://user-images.githubusercontent.com/4185874/144153210-64a93067-e58a-4b86-872f-418305ff7c9b.png)

What did you do for VISCfunctions?

2021-12-01 18:21 UTC, wfulp commented
I think I got access when I tried to incorporate Travis-CI. It pinged the owner of FredHutch org automatically. I think an email to scicomp@fredhutch.org should work.

2021-12-01 18:47 UTC, monicagerber commented
OK, this is allowed now and all actions are enabled. @wfulp let me know if you "approve" the changes.

2021-12-01 19:14 UTC, wfulp approved these changes
All checks passed on a test PR I just tried. 🥳

2021-12-01 21:21 UTC, monicagerber commented
Awesome, thanks for your help with this! 🎉

2021-12-01 21:22 UTC, merged