Feature/bama template
FredHutch/VISCtemplates pull request #88
Opened 2021-12-01 23:30 UTC by monicagerber

This PR builds on the template structure of a VISC report. I will discuss this PR at tomorrow's stand-up. 

Major changes:
* In the [PT report skeleton](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/rmarkdown/templates/visc_report/skeleton/skeleton.Rmd), the biological endpoints, lab methods, and statistical methods sections are set up as "child" R Markdown documents.
* There is a "generic" version and BAMA version of the methods (other assays will be added later), which can be created with [`use_visc_methods()`](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/R/template.R). 
* Instead of gently encouraging the user to use a project-level background section and study schema, this is more explicitly laid out in the PT report template. 

Minor changes:
* To improve the writing, editing, and reviewing experience, I used [semantic line breaks](https://sembr.org/) in the template text.
* Changed the names of the report templates (what you see in the R Studio GUI window) from ["Empty Report" to "VISC Empty Report"](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/rmarkdown/templates/visc_empty/template.yaml) and from ["VISC PT Report (Generic)" to "VISC PT Report"](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/rmarkdown/templates/visc_report/template.yaml).

Feedback:
* Alicia and Celia: Can you please comment on the methods language? This is taken directly from the current PT report template and BAMA assay memo that you wrote, so if you want to make update, this would be a good time. The files you should look at are: [`bama-biological-endpoints.Rmd`](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/templates/methods-bama/bama-biological-endpoints.Rmd), [`bama-lab-methods.Rmd`](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/templates/methods-bama/bama-lab-methods.Rmd), [`bama-statistical-methods.Rmd`](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/templates/methods-bama/bama-statistical-methods.Rmd), [`generic-biological-endpoints.Rmd`](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/templates/methods-generic/generic-biological-endpoints.Rmd), [`generic-lab-methods.Rmd`](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/templates/methods-generic/generic-lab-methods.Rmd), and [`generic-statistical-methods.Rmd`](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/templates/methods-generic/generic-statistical-methods.Rmd).
* Chelsey: We had a discussion about box plots in C100 but I'm not sure how that issue was resolved. Can you please take a look at [`bama-statistical-methods.Rmd`](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/templates/methods-bama/bama-statistical-methods.Rmd) and [`generic-statistical-methods.Rmd`](https://github.com/FredHutch/VISCtemplates/blob/9bf25b014970af97a628b59beaf692f5352cfaa2/inst/templates/methods-generic/generic-statistical-methods.Rmd) and suggest changes to the graphical analysis section that would help guide SRAs on this issue? We can chat about it and discuss approaches.
* Jimmy: Could you please look at the code in general and new function? I'm not sure if this is the best way to refer to the directories in `use_visc_methods()`.
* Others: General comments or other suggestions welcome.

2021-12-03 20:58 UTC, celiaeddy approved these changes
Monica, this is so great. I made a small change to the generic statistical methods doc, because I do think that should be mostly left for the analyst to write up (similar to the generic lab methods and endpoints sections). I thought the BAMA documents were great. Thank you so much for pulling this together.

2021-12-10 01:04 UTC, asatofh requested changes
Hi Monica,
I went through the sections you requested and added some comments and suggestions. Some comments may require further discussion.
Alicia

2021-12-10 03:43 UTC, celiaeddy commented on inst/templates/methods-bama/bama-statistical-methods.Rmd
> +at the screening dilution level.
this is sometimes 1:80, I suggest [1:50] so that people double check.

2021-12-13 18:17 UTC, monicagerber commented on inst/templates/methods-bama/bama-biological-endpoints.Rmd
> +[# antigens; list antigens]
@asatofh thanks for adding template language here

2021-12-13 18:19 UTC, monicagerber commented on inst/templates/methods-bama/bama-biological-endpoints.Rmd
> +Samples with blank MFI > 5000 were excluded from the analysis.
We agreed to delete this

2021-12-13 18:22 UTC, monicagerber commented on inst/templates/methods-bama/bama-statistical-methods.Rmd
> +Records were excluded at all visits if any of the following occurred at baseline:
We made a new section called exclusion criteria

2021-12-13 19:26 UTC, asatofh approved these changes
Monica,
I added some suggested template language based on Caskey 820 and made some small modifications to the table descriptions. Other than this, it looks good to close out! Thanks again for doing this, it's super helpful.
Alicia

2021-12-13 19:26 UTC, asatofh commented on inst/templates/methods-bama/bama-biological-endpoints.Rmd
> +[# antigens; list antigens]
```suggestion
[# antigens; list antigens or reference antigen summary table at end of sentence] 
```

2021-12-13 19:26 UTC, asatofh commented on inst/templates/methods-bama/bama-biological-endpoints.Rmd
> +[# antigens; list antigens]
Suggested language:
[For differential binding antigens only] The set includes antigens which highlight regions of differential binding to [insert target, e.g., the CD4 binding site of the HIV-1 envelope]. The differential binding set is comprised of [#] experimental [if applicable, (including the vaccine-matched antigen [insert vaccine-matched antigen])] and [#] matched reference antigens, where the reference antigens lack accessible target binding sites (knockout sites) present in the experimental antigens [reference tables]. [If applicable] An abbreviated name is used to simplify figures and tables included in this report and is proposed for each antigen [reference table].

2021-12-13 19:26 UTC, asatofh commented on inst/templates/methods-bama/bama-biological-endpoints.Rmd
> +<!-- Either in an antigen summary table or in the biological endpoints section, include information on antigen clade, any relevant panel information (e.g., antigen reagent project [ARP], see https://
```suggestion
<!-- Either in an antigen summary table or in the biological endpoints section, include information on antigen clade, any relevant panel information (e.g., antigen reagent project [ARP], see https://pubmed.ncbi.nlm.nih.gov/29386288/), sample size by antigen, positivity threshold, and whether a blank or a reference bead was used. For differential binding antigens, include a table of the experimental and paired reference antigens, abbreviated antigen names if used, and the target site for antibody binding. -->
```

2021-12-15 00:20 UTC, merged